# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', '\u5973'), ('male', '\u7537')], default='male', max_length=6),
        ),
    ]
